version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
          - 'astro-*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'prettier-plugin-tailwindcss'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-plugin-*'
      dev-dependencies:
        dependency-type: development
      expressive-code:
        patterns:
          - "astro-expressive-code"
          - "expressive-code"
          - "@expressive-code/*"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
